name: flutter_form_bloc_allenlinli
description: Create Beautiful Forms in Flutter. The easiest way to Prefill, Async Validation, Update Form Fields, and Show Progress, Failures or Navigate by Reacting to the Form State.
version: 0.32.0
homepage: https://github.com/allenlinli/form_bloc/tree/master/packages/flutter_form_bloc
repository: https://github.com/allenlinli/form_bloc/tree/master/packages/flutter_form_bloc
issue_tracker: https://github.com/allenlinli/form_bloc/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  form_bloc_allenlinli: ^0.32.0

  equatable: ^2.0.3
  rxdart: ^0.27.3
  flutter_keyboard_visibility_temp_fork: ^0.1.5
  collection: ^1.15.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
